### ISSUE TITLE
Add TMAP to project dependencies

### ISSUE THREAD

**Issue by niladell** [PaccMann/paccmann_datasets#15]
The `visualization` module uses [TMAP](http://tmap.gdb.tools) (alongside [faerun](https://github.com/reymond-group/faerun-python)) to generate the graphs.

It should be added to the project. However it is not available via `pip` and I am not sure what is the clean way of adding it (and adding it to the CI docker).

**Comment by drugilsberg** [comment]
It should be doable if we handle it as we with RDKit.

**Comment by jannisborn** [comment]
you can add `faerun` and `tmap` to the `requirements.txt`, the `setup.py` and for the CI most importantly to the `.conda.yml`. `tmap` only comes with conda not, with `pip`. Check the files in the polymer repo @niladell. But the build will probably fail anyways because of the `ujson` dependency of `faerun`. I'm not yet sure how to fix this.

**Comment by niladell** [comment]
> It should be doable if we handle it as we with RDKit.

This is by making our own fork and doing something like [this](https://github.com/drugilsberg/docker-rdkit-ubuntu) right?

>  for the CI most importantly to the `.conda.yml`

I thought that the CI was only looking at the `requeriments.txt` for running the tests. 

In any case, I'll check how it's set up now in the polymers repo and approach it the same way :)

**Comment by jannisborn** [comment]
Sorry, I mean the `.travis/Dockerfile`. Obviously, the `conda.yml` is only used upon creation of a new conda environment. If the CI would create it for testing, the conda.yml would be more or less self-contained, but travis does not create a conda env (I think the CI machines can't use `conda` which is why @drugilsberg created the docker image for rdkit).

**Comment by drugilsberg** [comment]
All more or less correct but the docker image with rdkit was only created to speed-up the CI avoiding to build rdkit every time (~5-10 minutes). A good approach would be to create another image with tmap installed as well, that we use to run the tests im pytoda.
