### ISSUE TITLE
Truly Lazy Datasets (netcdf, hdf5)

### ISSUE THREAD

**Issue by jannisborn** [PaccMann/paccmann_datasets#36]
To train on large DBs like ZINC, we should create a super lazy SMILES dataset class, conceptually like this:

```
class _SMILESLDataset(torch.utils.Dataset):
    def __init__(self, data_dir):
        self.data_files = os.listdir(data_dir)
        sort(self.data_files)

    def __getitem__(self, idx):
        return load_file(self.data_files[idx])

    def __len__(self):
        return len(self.data_files)
```
Then we can create a loader with multiple workers.

I think it should not support any RDKit operations or SMILES language transforms. SELFIES should be supported though.

**Comment by drugilsberg** [comment]
Hi @jannisborn the _lazy_ datasets follows the same principle by doing a setup at construction of the dataset and caching processed data on disk for key-values fast access. This might take a lot of time in the `__init__` but it guarantees performance on training where we mostly need it.
See [this class](https://github.com/PaccMann/paccmann_datasets/blob/master/pytoda/datasets/_smi_lazy_dataset.py#L15) for a concrete example.

The approach you sketched there has the problem that `load_file(self.data_files[idx])` forces to open and close a file when fetching each item of the batch in `__getitem__`.
While this drastically reduce `__init__` time, it will kill performance when assembling batches for training (open/close for each batch sample puts a crazy pressure on I/O).

A solution might be to create processed data in a format like [HDF5](https://support.hdfgroup.org/HDF5/whatishdf5.html) or [NetCDF](https://www.unidata.ucar.edu/software/netcdf/).
These data formats allows for indexed storage and should be ideal in a context like this one.
We could write a generic method in [_CacheDataset](https://github.com/PaccMann/paccmann_datasets/blob/3885e3d775e1ce5b8cd5be6674aaec8225c29901/pytoda/datasets/_cache_dataset.py#L8) that dumps the cached data to these formats:

```python
def to_netcdf(self, filepath: str) -> None:
        """
        Store the cached data in NetCDF format.

        Args:
             filepath (str): path where to store the data.
        """
        # TODO: implement with xarray library making sure we index samples with the
        # index used in __getitem__.

def to_hdf5(self, filepath: str) -> None:
        """
        Store the cached data in HDF5 format.

        Args:
             filepath (str): path where to store the data.
        """
        # TODO: implement with h5py library making sure we index samples with the
        # index used in __getitem__.
```

At this point we can do the **setup once and store in a hierarchical/indexed format the processed data**.

We then just need specific classes to just read those data. The beauty of this is that **since the datasets are already processed we don't need to create a class for the specific data modality**, but a generic implementation should do the trick.

```python
from typing import Any
from torch.utils.data import Dataset


class HDF5Dataset(Dataset):
    """
    Dataset parsing samples from an HDF5 file.
    """

    def __init__(self, filepath) -> None:
        """Initialize the dataset."""
        Dataset.__init__(self)
        self.filepath = filepath
        # TODO: get a file handle that support indexing for __getitem__.
        self.handle = open_file(self.filepath)

    def __getitem__(self, index: int) -> Any:
        """
        Get the sample a given index.
        
        Args:
            index (int): index of the sample to retrieve.
        
        Returns:
            Any: the sample retrieved from disk.
        """
        # TODO: implement the right logic
        return self.handle[index]

    def __len__(self) -> int:
        """Get number of samples."""
        # TODO: implement the right logic
        return len(self.handle)


class NetCDFDataset(Dataset):
    """
    Dataset parsing samples from an NetCDF file.
    """

    def __init__(self, filepath) -> None:
        """Initialize the dataset."""
        Dataset.__init__(self)
        self.filepath = filepath
        # TODO: get a file handle that support indexing for __getitem__.
        self.handle = open_file(self.filepath)

    def __getitem__(self, index: int) -> Any:
        """
        Get the sample a given index.
        
        Args:
            index (int): index of the sample to retrieve.
        
        Returns:
            Any: the sample retrieved from disk.
        """
        # TODO: implement the right logic
        return self.handle[index]

    def __len__(self) -> int:
        """Get number of samples."""
        # TODO: implement the right logic
        return len(self.handle)
```

What do you think? This is probably the best way to do not sacrifice data processing and have something that create batches in a feasible time.

Regarding the specific data format to support I have no preferenes. I and @C-nit used NetCDF heavily in this project: https://github.com/PhosphorylatedRabbits/mass_spec_trans_coding/.
But HDF5 is as popular and should work as well.

**Comment by jannisborn** [comment]
Sounds good to me, the thing I'm not sure about is whether it will work well together with having multiple workers in the loader (`num_workers`), e.g. see [here](https://discuss.pytorch.org/t/dataloader-when-num-worker-0-there-is-bug/25643/2).

**Comment by drugilsberg** [comment]
We can probably have a way to ensure that the file is open with a cheap call.

**Comment by niladell** [comment]
I did work a bit with hdf5 files when training models (with TF tho) with images and concurrent reading with multiple workers was not a problem. The loader we used was very similar to the one that @drugilsberg proposed.

**Comment by jannisborn** [comment]
Issue can be closed since the new `SMILESTokenizerDataset` has an `iterate_dataset` option which makes dataset setup fairly fast (~2M SMILES dataset can be set up in <5 sec).

**Comment by C-nit** [comment]
Reopened this with the issue renamed, since the idea of having Datasets that read lazily from files is still a good idea, aside from the SMILESTokenizerDataset being fast in the case it does not need to build the vocab.
