### ISSUE TITLE
selfies 1.0 release

### ISSUE THREAD

**Issue by C-nit** [PaccMann/paccmann_datasets#81]
our tests for selfies tokenization fail for newer versions of the `selfies` dependency.
```
FAIL: test_tokenize_selfies (pytoda.smiles.tests.test_processing.TestProcessing)
Test tokenize_selfies.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dow/public_dev/paccmann_datasets/pytoda/smiles/tests/test_processing.py", line 142, in test_tokenize_selfies
    self.assertListEqual(tokenize_selfies(selfies), ground_truth)
AssertionError: Lists differ: ['[C]', '[C]', '[=N]', '[O]', '[C]', '[Expl=Ring1]', '[Branch1_1]'] != ['[c]', '[c]', '[n]', '[o]', '[c]', '[Ring1]', '[Ring2]']

First differing element 0:
'[C]'
'[c]'

- ['[C]', '[C]', '[=N]', '[O]', '[C]', '[Expl=Ring1]', '[Branch1_1]']
?    ^      ^      ^^      ^      ^      -----           ^^^ ^^^^^

+ ['[c]', '[c]', '[n]', '[o]', '[c]', '[Ring1]', '[Ring2]']
?    ^      ^      ^      ^      ^                 ^^ ^^


```
we should require a version  >1 in setup.py, pin an up to date version in requirements.txt and adapt the tests for correct selfies tokens. 
See https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md

Besides these obvious task, there is now [`selfies.utils.split_selfies`](https://github.com/aspuru-guzik-group/selfies/blob/9f822e175e559fa11753b715991645afe9953621/selfies/utils.py#L25).
Could it replace our implementation of `tokenize_selfies` altogether @jannisborn ?

**Comment by jannisborn** [comment]
@C-nit 
This mismatch was introduced via `selfies==1.0.0`. I clarified it with the developers [here](https://github.com/aspuru-guzik-group/selfies/issues/26) and it indeed seems right to adapt the unittests on our side. I agree also on requiring/pinning versions in setup and requirements. I haven't found the time to fix this since it didn't seem high priority.

Regarding the tokenizers, it's great that selfies has a build-in tokenizer now! I think we should keep our coding scaffold, not only for backwards compatbility but also since it's well integrated into the codeflow. I suggest to keep`tokenize_selfies` but we could add a flag `use_selfies_tokenizer` which, if set, actually makes `tokenize_selfies` to only call `selfies.utils.split_selfies`. The default of the flag could even be True.

But the first thing would obviously be to verify how different the two tokenizers are.

**Comment by C-nit** [comment]
I don't think compatibility is a problem here since the selfies introduces breaking changes anyway.

I hope they are the same and we can just replace the 'selfies' value in `TOKENIZER_FUNCTIONS` and use the function as default for selfies use cases.

One can still pass the old method directly with newer versions in any case. We can even keep it in the library, I would just not expose it in the factory, at least not under the key 'selfies' (that is quite new and probably not used by cases concerning backwards compatibility).

**Comment by jannisborn** [comment]
Agreed. Do you want to wrap it up from here or shall I do it?
