### ISSUE TITLE
transform_encoding in smiles_language.py

### ISSUE THREAD

**Issue by hmkim** [PaccMann/paccmann_datasets#97]
Hi!

In my test (e.g paccmann_predictor/examples/train_paccmann.py) ,  I checked this function no defined in this script (smiles_language.py) 

Could you check this issue?

![스크린샷 2020-11-10 오후 4 50 05](https://user-images.githubusercontent.com/4966343/98645088-ca2c2000-2374-11eb-80d2-d8808631f0a4.png)

Thank you in advance!

**Comment by hmkim** [comment]
In sure, I ran the code with 0.0.3 version of paccman_datasets . Do you have the release plan of **paccman_predictor** that with latest version of paccman_datasets.

**Comment by jannisborn** [comment]
Thanks for your interest.
If you indeed use `pytoda==0.0.3`, I would not expect this error since SMILESLanguage has no attribute `transform_encoding` in that version. See [here](https://github.com/PaccMann/paccmann_datasets/blob/0.0.3/pytoda/smiles/smiles_language.py). That attribute was introduced in version 0.2. 
To me it looks like you have `pytoda>=0.2` and you are passing an existing SMILESLanguage object (a `.pkl` file) to the training script. The easiest way to solve this is a downgrade in `pytoda`. Otherwise, if you want to stick to a newer release of pytoda, you can either create a new SMILESLanguage object or port the existing one, both is describe [here](https://github.com/PaccMann/paccmann_datasets/tree/master/examples).

**Comment by hmkim** [comment]
I'm sorry. 
I mean I ran the code with pytoda==0.0.3 sucessfully.

**Comment by C-nit** [comment]
Glad you could resolve the issue by using the matching pytoda version for your training script.

> Do you have the release plan of **paccman_predictor** that with latest version of paccman_datasets.  

Thank you for bringing this up.  
Technically the `paccmann_predictor` package does not depend on `pytoda`, though of course the example training script does (and is found next to a file pinning the requirements for it).

We are aware that the training scripts are actually the way `pytoda` is used, and that we do not provide yet any examples on the Datasets with refactored Languages. We might release such examples when we are reasonably sure that the API is stable, but we need to gather some more experience with the new version.
